language: bash

services:
  - docker

env:
  matrix:
    - PHP_VER=7.2
    - PHP_VER=7.1
    - PHP_VER=7.0
    - PHP_VER=5.6

script:
  - set -e
  - make test
  - cp docker.mk Makefile
  - tar -czf php4docker.tar.gz docker-compose.yml docker-sync.yml Makefile .env traefik.yml

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - php4docker.tar.gz
  on:
    tags: true
